name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

jobs:
  clippy:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          args: --all-features  --all-targets --color always -- --deny warnings

  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Install protoc
        run: sudo apt install -y protobuf-compiler
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        name: cargo build
        with:
          command: build
          args: --release --all-features
      - uses: actions-rs/cargo@v1
        name: cargo test
        with:
          command: test
          args: --all-targets --benches